import LeanIntro.Playground.CHSH.Action

/-!
# Lemma 3.1 / 4.1 — Automorphism Group Proofs, restated and audited standalone

This file adds nothing mathematically new to `Playground/CHSH/Aut.lean` and
`Playground/CHSH/Action.lean`; it exists purely to give the thesis's Lemma 3.1
(§3.2.3) / Lemma 4.1 (§7.1) a *single, literally-matching* Lean statement, and to
audit exactly that statement's axiom footprint in isolation from the rest of the
development (the Sheaf/Equivariance/Rigidity material, which answers Lemma 4.2–4.4
and is out of scope here).

Lemma 3.1 (Group Closure and Action Laws on Poset `M`). Let `G = D4` be the
symmetry group acting on the 8-cell CHSH poset `M`. The action map
`· : G × M → M` satisfies the group action axioms:

    1 · x = x,   g · (h · x) = (g h) · x   ∀ g, h ∈ G, x ∈ M

together with the closure statement implicit in "the action map `G × M → M`" — that
the action of `G` never leaves `M`.
-/

namespace CHSH

open Meas CategoryTheory

/-! ### (0) `G ≅ D₄`, i.e. `G` really is the dihedral group of order 8

This is presupposed by the lemma statement ("Let `G = D4`"), so it belongs to the
automorphism-group proof even though it is proved in `Aut.lean`. -/

/-- **`G` is the dihedral group of order 8.** An explicit isomorphism, kernel-checked. -/
theorem chsh_G_isom_D4 : Nonempty (G ≃* DihedralGroup 4) := ⟨gEquivDihedral⟩

theorem chsh_G_card_eight : Nat.card G = 8 := card_G

/-! ### (1) Closure: the action map `G × M → M` is total

`SMul G M` is a *function* `G → M → M`; that it type-checks at all is the closure
law — every `g • S` for `S : M` (an 8-cell) is again a term of `M`, i.e. again one
of the 8 cells. The content is in `image_mem_cells`, which is what the `SMul`
instance in `Action.lean` invokes to produce the second component of the subtype. We
restate it here as an explicit closure theorem so the correspondence with the
informal lemma is not just "the code type-checks" but a named, checkable fact. -/

/-- **Closure.** Acting by any `g ∈ G` on any cell of `M` produces a cell of `M`. -/
theorem chsh_action_closed (g : G) (S : M) : (g • S).val ∈ cells :=
  (g • S).property

/-- Unpacked at the level of `Finset Meas`: relabelling a cell's underlying finite set
of measurements by a hypergraph automorphism keeps it inside the 8-element `cells`
family (4 singletons + 4 contexts). This is the same fact restated without going
through the `M`/`SMul` packaging, to make the closure claim checkable independently
of how the action was packaged as a subtype action. -/
theorem chsh_action_closed' (σ : Equiv.Perm Meas) (hσ : σ ∈ G) {S : Finset Meas}
    (hS : S ∈ cells) : S.image σ ∈ cells :=
  image_mem_cells σ hσ hS

/-! ### (2) Identity law: `1 · x = x` -/

/-- **Identity law.** The identity element of `G` fixes every cell of `M`. -/
theorem chsh_action_identity (x : M) : (1 : G) • x = x :=
  one_smul G x

/-! ### (3) Compatibility law: `g · (h · x) = (g h) · x` -/

/-- **Compatibility law.** The action is associative with the group multiplication. -/
theorem chsh_action_compatibility (g h : G) (x : M) : g • (h • x) = (g * h) • x :=
  (mul_smul g h x).symm

/-! ### (4) The three laws packaged as one term, matching "the action map `α : G × M → M`
satisfies the group action axioms" verbatim -/

set_option warn.classDefReducibility false in
/-- **Lemma 3.1 / 4.1, packaged.** `G` acts on `M` (closure is the type of `•`
itself), the identity law and the compatibility law both hold, kernel-checked. This
is definitionally the `MulAction G M` instance from `Action.lean`; naming it here is
what lets `#print axioms CHSH.chsh_is_group_action` audit it under a name chosen to
match the lemma, rather than an autogenerated one. -/
def chsh_is_group_action : MulAction G M where
  one_smul := chsh_action_identity
  mul_smul g h x := (chsh_action_compatibility g h x).symm

/-! ### (5) The action is functorial, matching §1.6's "instantiate its action as a
covariant functor `α : SingleObj G ⥤ Cat`" -/

/-- Functoriality of the action restated: the identity element induces the identity
functor, and composition of group elements induces composition of functors (in the
order fixed by `End.mul_def`). This is exactly the categorical repackaging of (2)
and (3) above. -/
theorem chsh_action_functorial :
    (α.map (SingleObj.toEnd G 1)).toFunctor = 𝟭 M ∧
    ∀ g h : G, (α.map (SingleObj.toEnd G (g * h))).toFunctor = actFunctor h ⋙ actFunctor g :=
  ⟨α_map_one, α_map_mul⟩

/-! ### (6) Sanity: the action is faithful and non-trivial, so it is *the* CHSH
symmetry action and not some degenerate stand-in (e.g. the trivial action, which
would vacuously satisfy (1)–(3)). -/

theorem chsh_action_faithful : Function.Injective (MulAction.toPermHom G M) := faithful

theorem chsh_action_nontrivial : ∃ (g : G) (S : M), g • S ≠ S := exists_smul_ne

#print axioms chsh_G_isom_D4
#print axioms chsh_G_card_eight
#print axioms chsh_action_closed
#print axioms chsh_action_closed'
#print axioms chsh_action_identity
#print axioms chsh_action_compatibility
#print axioms chsh_is_group_action
#print axioms chsh_action_functorial
#print axioms chsh_action_faithful
#print axioms chsh_action_nontrivial

end CHSH

/-! ## Axiom audit, scoped to the automorphism-group proof only

Checks that every declaration making up the proof of Lemma 3.1 / 4.1 — the
dihedral isomorphism, the closure law, the identity law, the compatibility law, the
packaged `MulAction` instance, the functorial repackaging, and the non-degeneracy
sanity checks — rests on nothing beyond Lean's three standard axioms. In particular
this fails the build if any of them silently depended on `sorryAx` (an unfinished
proof) or `Lean.ofReduceBool` (a `native_decide`, i.e. a kernel-external
computation). -/

open Lean Elab Command in
run_cmd do
  let allowed : List Name := [``propext, ``Classical.choice, ``Quot.sound]
  let decls : List Name :=
    [ -- prerequisite: G is the automorphism group and is isomorphic to D4
      ``Hypergraph.autSubgroup
    , ``Hypergraph.image_id
    , ``Hypergraph.mem_autSubgroup_ofFinsetFamily
    , ``CHSH.rot_mem
    , ``CHSH.reflect_mem
    , ``CHSH.rot_pow_four
    , ``CHSH.rot_pow_two_ne_one
    , ``CHSH.orderOf_rot
    , ``CHSH.reflect_sq
    , ``CHSH.reflect_mul_rot
    , ``CHSH.hom
    , ``CHSH.hom_injective
    , ``CHSH.range_hom
    , ``CHSH.gEquivDihedral
    , ``CHSH.card_G
    , ``CHSH.card_G_by_enumeration
    , ``CHSH.chsh_G_isom_D4
    , ``CHSH.chsh_G_card_eight
      -- the lemma proper: closure, identity, compatibility
    , ``CHSH.image_mem_cells
    , ``CHSH.chsh_action_closed
    , ``CHSH.chsh_action_closed'
    , ``CHSH.chsh_action_identity
    , ``CHSH.chsh_action_compatibility
    , ``CHSH.chsh_is_group_action
      -- functorial repackaging (§1.6's α : SingleObj G ⥤ Cat)
    , ``CHSH.actFunctor_one
    , ``CHSH.actFunctor_mul
    , ``CHSH.α
    , ``CHSH.α_map_one
    , ``CHSH.α_map_mul
    , ``CHSH.chsh_action_functorial
      -- non-degeneracy sanity checks
    , ``CHSH.faithful
    , ``CHSH.exists_smul_ne
    , ``CHSH.chsh_action_faithful
    , ``CHSH.chsh_action_nontrivial
    , ``CHSH.G_ne_top
    , ``CHSH.G_ne_bot
      -- G is the right group (not an artefact of the encoding)
    , ``CHSH.mem_G_iff_graph_aut
    , ``CHSH.swapParties_mem
    , ``CHSH.card_partyPreserving_aut ]
  let mut report := #[]
  for d in decls do
    let axs ← liftCoreM <| collectAxioms d
    for a in axs do
      unless allowed.contains a do
        throwError m!"axiom audit failed: `{d}` depends on `{a}`"
    report := report.push m!"  {d} — {axs.toList}"
  logInfo <| m!"automorphism-group-proof axiom audit passed \
    ({decls.length} declarations, standard axioms only: propext, Classical.choice, Quot.sound)\n"
    ++ MessageData.joinSep report.toList "\n"
